# Generated by Django 3.1.4 on 2021-03-15 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image01',
            field=models.ImageField(default=False, upload_to='product_image'),
        ),
        migrations.AddField(
            model_name='product',
            name='image02',
            field=models.ImageField(default=False, upload_to='product_image'),
        ),
    ]
