# Generated by Django 3.1.4 on 2021-03-15 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='board_dicription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.TextField(max_length=500)),
                ('link', models.CharField(max_length=100, null=True)),
                ('link01', models.CharField(max_length=100, null=True)),
                ('link02', models.CharField(max_length=100, null=True)),
                ('link04', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(default=False, upload_to='Board_member_image')),
            ],
        ),
    ]
