# Generated by Django 3.1.4 on 2021-03-15 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_auto_20210315_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='position',
            field=models.CharField(max_length=500),
        ),
    ]
