# Generated by Django 3.1.4 on 2021-03-15 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0005_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='subject',
            new_name='subjects',
        ),
    ]
