# Generated by Django 3.1.4 on 2021-03-15 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0006_auto_20210315_2012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='subjects',
            new_name='Sub',
        ),
    ]
