# Generated by Django 3.1.4 on 2021-03-15 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0008_auto_20210315_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='subjects',
            field=models.CharField(max_length=100),
        ),
    ]
